apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meilisearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:juergenrockmann/meilisearch.git'
    targetRevision: main
    path: infra-helm-argo/apps/meilisearch
    helm:
      releaseName: meilisearch
      valueFiles:
        - clusters/prod/meilisearch-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
